const socket=io(),$=id=>document.getElementById(id);let state=null,identity=null,lastQuestion='',result=null;
const colors=['#955436','#a7d7ee','#d78ab9','#f4a344','#e74d49','#f4df49','#40a76d','#345cb8'];
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'$'+Number(n).toLocaleString();
function send(event,payload={}){socket.emit(event,payload,res=>{if(!res?.ok)$('actionError').textContent=res?.error||'Request failed';else $('actionError').textContent='';});}
function createRoom(){socket.emit('create',{name:$('name').value},joinCallback);}
function joinRoom(){socket.emit('join',{code:$('roomInput').value,name:$('name').value},joinCallback);}
function joinCallback(res){if(!res.ok){$('error').textContent=res.error;return;}identity={code:res.code,id:res.id,token:res.token};localStorage.setItem('sti-session',JSON.stringify(identity));$('error').textContent='';}
const saved=JSON.parse(localStorage.getItem('sti-session')||'null');if(saved)socket.on('connect',()=>socket.emit('join',{code:saved.code,token:saved.token},res=>{if(res.ok)identity=saved;else localStorage.removeItem('sti-session');}));
socket.on('answerResult',r=>{result=r;render();});
socket.on('state',s=>{state=s;$('lobby').classList.add('hidden');$('game').classList.remove('hidden');$('roomBadge').textContent='Room '+s.code;$('hostDisplayLink').href='/display.html?code='+encodeURIComponent(s.code);render();});
function render(){if(!state)return;drawBoard();drawPlayers();drawActions();drawTrade();$('log').innerHTML=state.log.slice().reverse().map(s=>'<p>'+escapeHtml(s)+'</p>').join('');if(state.ended)showLeaderboard();else if(state.phase==='quiz'&&state.pending?.player===state.self&&lastQuestion!==state.pending.question){lastQuestion=state.pending.question;showQuestion();}else if(state.phase==='review'&&result)showResult();else if(state.phase!=='quiz'&&state.phase!=='review'){lastQuestion='';result=null;closeModal();}}
function drawBoard(){const el=$('board');el.innerHTML='<div class="center"><strong>STI-OPOLY</strong><p>Nursing School Edition</p><p>Chapter 44 • 10 players</p><p>🎲 '+(state.dice?state.dice.join(' + '):'Ready to roll')+'</p></div>';state.spaces.forEach((s,i)=>{let row,col;if(i<=10){row=11;col=11-i;}else if(i<=20){row=11-(i-10);col=1;}else if(i<=30){row=1;col=i-19;}else{row=i-29;col=11;}const d=document.createElement('div');d.className='tile';d.style.gridRow=row;d.style.gridColumn=col;if([0,10,20,30].includes(i))d.style.background='#d5e7d9';const owner=state.players.find(p=>p.id===s.owner);d.innerHTML=`<div class="stripe" style="background:${s.group>=0?colors[s.group]:'transparent'}"></div><b>${escapeHtml(s.name)}</b><small>${s.price&&['property','rail','utility'].includes(s.type)?money(s.price):''}</small><div class="tokens">${state.players.filter(p=>p.alive&&p.pos===i).map(p=>p.icon).join('')}</div>${owner?`<span style="position:absolute;right:2px;top:2px;background:${owner.color};width:9px;height:9px;border-radius:50%"></span>`:''}`;d.title=s.name+(owner?' • Owner: '+owner.name:'');el.append(d);});}
function drawPlayers(){$('players').innerHTML=state.players.map(p=>`<div class="person ${p.id===state.turn?'current':''}"><span>${p.icon}</span><span>${escapeHtml(p.name)}${p.id===state.self?' (you)':''}${!p.connected?' ◌':''}${!p.alive?' (out)':''}<br><small>🎟️ ${p.freeCard} · ${state.spaces.filter(s=>s.owner===p.id).length} deeds</small></span><span>${money(p.money)}</span></div>`).join('');}
function action(label,fn,cls=''){return `<button class="${cls}" onclick="${fn}">${label}</button>`;}
function drawActions(){const me=state.players.find(p=>p.id===state.self),current=state.players.find(p=>p.id===state.turn),mine=me?.id===state.turn;let a='';$('phaseTitle').textContent=state.ended?'Final results':state.started?'Current turn':'Waiting room';$('turnInfo').innerHTML=state.ended?'Game over':state.started?`<b>${escapeHtml(current?.name||'')}</b> · ${escapeHtml(state.phase)} ${state.dice?'· 🎲 '+state.dice.join(' + '):''}`:`<b>${state.players.length}/10 joined</b><p>Share code <strong>${state.code}</strong> with classmates.</p>`;
if(!state.started&&state.self===state.host)a+=action('Start game','send("start")');
if(state.started&&!state.ended&&mine){if(state.phase==='roll'){a+=action('🎲 Roll dice','send("roll")');if(me.jail){a+=action('🎟️ Use free card','send("detention",{useCard:true})','secondary');a+=action('Pay $50','send("detention",{useCard:false})','secondary');}}if(state.phase==='buy'){const s=state.spaces[me.pos];a+=`<p>Buy ${escapeHtml(s.name)} for ${money(s.price)}?</p>`+action('Purchase','send("buy",{buy:true})')+action('Pass','send("buy",{buy:false})','light');}if(state.phase==='end')a+=action('End turn →','send("endTurn")');if(state.phase==='quiz')a+='<p>Answer the question on your screen.</p>';if(state.phase==='review')a+=action('Continue','send("reviewDone")');}
if(state.started&&!state.ended&&state.self===state.host)a+=action('🏆 End game / leaderboard','confirmFinish()','light');$('actions').innerHTML=a;}
function showModal(html){$('modal').innerHTML=html;$('overlay').classList.remove('hidden');}function closeModal(){$('overlay').classList.add('hidden');}
function showQuestion(){const q=state.pending;showModal(`<h2>📘 Nursing question</h2><p>${escapeHtml(q.question)}</p>${q.options.map((o,i)=>`<button class="option" onclick="answer(${i})">${String.fromCharCode(65+i)}. ${escapeHtml(o)}</button>`).join('')}<p class="muted">Wrong answer = all properties return to the bank.</p>`);}
function answer(choice){send('answer',{choice});closeModal();}
function showResult(){showModal(`<h2>${result.correct?'✅ Correct!':'❌ Incorrect'}</h2><p><b>Correct answer:</b> ${escapeHtml(result.correctAnswer)}</p><p>${escapeHtml(result.rationale)}</p><p>${result.correct?'Your game card reward or penalty has been applied.':'All your properties were forfeited to the bank.'}</p><button onclick="send('reviewDone');result=null;closeModal()">Continue</button>`);}
function drawTrade(){const t=state.trade,me=state.self;if(!t){$('tradeNotice').innerHTML='';return;}const from=state.players.find(p=>p.id===t.from),to=state.players.find(p=>p.id===t.to);let text=`<p>${escapeHtml(from.name)} offered ${t.give.map(i=>state.spaces[i].name).join(', ')||'no deeds'} + ${money(t.giveCash)} for ${t.take.map(i=>state.spaces[i].name).join(', ')||'no deeds'} + ${money(t.takeCash)} from ${escapeHtml(to.name)}.</p>`;if(me===t.to)text+=action('Accept','send("tradeReply",{accept:true})','secondary')+' '+action('Decline','send("tradeReply",{accept:false})');$('tradeNotice').innerHTML=text;}
function openTrade(){if(!state?.started||state.ended){alert('Start the game first.');return;}if(state.trade){alert('A trade is already pending.');return;}const me=state.players.find(p=>p.id===state.self);if(!me.alive)return;const others=state.players.filter(p=>p.alive&&p.id!==me.id);showModal(`<h2>🤝 Propose a trade</h2><label>Trade with <select id="partner" onchange="tradeFields()">${others.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('')}</select></label><div id="tradeFields"></div><button onclick="submitTrade()">Send offer</button> <button class="light" onclick="closeModal()">Cancel</button>`);tradeFields();}
function tradeFields(){const me=state.self,to=$('partner').value;const mine=state.spaces.map((s,i)=>({...s,i})).filter(s=>s.owner===me),theirs=state.spaces.map((s,i)=>({...s,i})).filter(s=>s.owner===to);const checks=(list,name)=>list.length?list.map(s=>`<label class="check"><input type="checkbox" name="${name}" value="${s.i}"> ${escapeHtml(s.name)}</label>`).join(''):'<p class="muted">No properties</p>';$('tradeFields').innerHTML=`<h3>Properties you give</h3>${checks(mine,'give')}<h3>Properties you request</h3>${checks(theirs,'take')}<label>Cash you give <input id="giveCash" type="number" min="0" value="0"></label><label>Cash you request <input id="takeCash" type="number" min="0" value="0"></label>`;}
function submitTrade(){const checked=n=>[...document.querySelectorAll(`input[name="${n}"]:checked`)].map(x=>Number(x.value));send('tradeOffer',{to:$('partner').value,give:checked('give'),take:checked('take'),giveCash:Number($('giveCash').value),takeCash:Number($('takeCash').value)});closeModal();}
function confirmFinish(){if(confirm('End the game for everyone and show the leaderboard?'))send('finish');}
function showLeaderboard(){closeModal();$('phaseTitle').textContent='🏆 Final leaderboard';$('actions').innerHTML='';$('turnInfo').innerHTML=state.leaderboard.map(p=>`<div class="leader"><b>${p.rank===1?'🥇':p.rank===2?'🥈':p.rank===3?'🥉':'#'+p.rank} ${escapeHtml(p.name)}</b><span>${money(p.netWorth)}</span></div>`).join('');}
