const colors=['#955436','#a7d7ee','#d78ab9','#f4a344','#e74d49','#f4df49','#40a76d','#345cb8'];
const T=(name,type,price=0,group=-1)=>({name,type,price,group,owner:-1});
const spaces=[T('GO • Wellness','go'),T('Chlamydia','property',60,0),T('Community Care','community'),T('Gonorrhea','property',60,0),T('Clinic Fees','tax',200),T('Community Clinic','rail',200),T('Urethritis','property',100,1),T('Chance','chance'),T('Cervicitis','property',100,1),T('PID','property',120,1),T('Detention / Visiting','jail'),T('Trichomoniasis','property',140,2),T('NAAT Lab','utility',150),T('Vulvovaginitis','property',140,2),T('Proctitis','property',160,2),T('Student Health Clinic','rail',200),T('HSV-1','property',180,3),T('Community Care','community'),T('HSV-2','property',180,3),T('Herpes Recurrence','property',200,3),T('Free Parking','free'),T('Primary Syphilis','property',220,4),T('Chance','chance'),T('Secondary Syphilis','property',220,4),T('Latent Syphilis','property',240,4),T('Public Health Clinic','rail',200),T('HPV Low-Risk','property',260,5),T('HPV High-Risk','property',260,5),T('HPV Screening','property',280,5),T('Follow-up Fees','tax',100),T('Go to Detention','goto'),T('Hepatitis B','property',300,6),T('Hepatitis C','property',300,6),T('Community Care','community'),T('Partner Care','property',320,6),T('Specialty Clinic','rail',200),T('Diagnostic Testing','chance'),T('Syphilis Treatment','property',350,7),T('Serology Lab','utility',150),T('STI Prevention','property',400,7)];
const questions=[
['Which organism causes chlamydia?',['Treponema pallidum','Chlamydia trachomatis','Trichomonas vaginalis','HSV-2'],1,'Chlamydia is caused by the bacterium Chlamydia trachomatis.'],
['Which test detects chlamydial DNA or RNA in urine or genital specimens?',['NAAT','RPR','VDRL','Skin biopsy'],0,'Nucleic acid amplification testing (NAAT) identifies chlamydial genetic material.'],
['What complication can develop when cervicitis spreads into the upper genital tract?',['Scabies','PID','Genital warts','Oral herpes'],1,'Ascending infection can cause pelvic inflammatory disease (PID).'],
['What organism causes gonorrhea?',['Neisseria gonorrhoeae','Candida albicans','Treponema pallidum','HPV'],0,'Gonorrhea is caused by Neisseria gonorrhoeae.'],
['Which medication is listed for gonorrhea in Chapter 44?',['Acyclovir','Ceftriaxone','Metronidazole','Imiquimod'],1,'The chapter lists the cephalosporin ceftriaxone for gonorrhea.'],
['A painless chancre is characteristic of which stage?',['Secondary syphilis','Primary syphilis','Tertiary syphilis','Latent syphilis'],1,'Primary syphilis typically causes a painless chancre.'],
['Which finding is typical of secondary syphilis?',['Rash on palms and soles','Strawberry cervix','Pubic lice','Frothy discharge'],0,'Secondary syphilis can cause a rash involving the palms and soles.'],
['Which are nontreponemal syphilis tests?',['NAAT and PCR','RPR and VDRL','Pap and HPV test','Culture and wet mount'],1,'RPR and VDRL are nontreponemal tests used in syphilis evaluation.'],
['What is the treatment of choice for syphilis according to Chapter 44?',['Penicillin G','Acyclovir','Permethrin','Tinidazole'],0,'The chapter identifies penicillin G as the treatment of choice.'],
['Which pathogen causes trichomoniasis?',['A virus','A fungus','A protozoan parasite','A spirochete'],2,'Trichomonas vaginalis is a protozoan parasite.'],
['Which finding is associated with trichomoniasis?',['Painless chancre','Strawberry cervix','Gummas','Cauliflower-like warts'],1,'A strawberry cervix may be seen with trichomoniasis.'],
['Which drug is listed for trichomoniasis?',['Metronidazole','Valacyclovir','Ceftriaxone','Penicillin G'],0,'The chapter lists metronidazole or tinidazole.'],
['Which viruses cause herpes simplex infection?',['HSV-1 and HSV-2','HPV-6 and HPV-11','HBV and HCV','HIV only'],0,'Herpes simplex infection is caused by HSV-1 or HSV-2.'],
['Which medication can reduce herpes symptoms and recurrences?',['Acyclovir','Cefixime','Amoxicillin','Permethrin'],0,'Acyclovir is an antiviral listed for herpes. It does not cure HSV.'],
['Which HPV types are commonly linked to genital warts?',['High-risk only','Low-risk HPV','Hepatitis viruses','HSV-1'],1,'Low-risk HPV types can cause genital warts.'],
['High-risk HPV is associated with which complication?',['Cancer','PID only','Scabies','Urethritis only'],0,'High-risk HPV is linked with several cancers, including cervical cancer.'],
['Which treatment may be used to remove genital warts?',['Cryotherapy','Penicillin G','Ceftriaxone','RPR'],0,'Cryotherapy freezes warts, but removal does not cure HPV infection.'],
['What may occur after untreated PID?',['Infertility and ectopic pregnancy risk','Permanent immunity','Guaranteed recovery without care','Only a skin rash'],0,'Scarring and adhesions from PID can cause infertility and raise ectopic pregnancy risk.'],
['What should a nurse prioritize when discussing an STI diagnosis?',['Judgmental questioning','Privacy and nonjudgmental communication','Sharing the diagnosis with friends','Avoiding education'],1,'The chapter emphasizes acceptance, privacy, sensitivity, and therapeutic communication.'],
['Which STI may be passed to a newborn during childbirth and cause eye infection?',['Gonorrhea','Scabies only','Genital warts only','Latent syphilis only'],0,'Gonorrhea can cause ophthalmia neonatorum in newborns.'],
['What can increase STI transmission risk according to Chapter 44?',['Consistent barrier use','Inconsistent condom use','Prompt treatment','Screening'],1,'Inconsistent or inappropriate condom use is listed as a risk factor.'],
['Which statement about genital herpes is accurate?',['It is always symptomatic','Antivirals eradicate the virus','It can recur after dormant periods','It is caused by a bacterium'],2,'HSV can remain dormant in nervous tissue and reactivate.'],
['Which organisms are primary sources of PID?',['Chlamydia and gonorrhea','Pubic lice and scabies','HPV and hepatitis C only','HSV and HPV only'],0,'The chapter identifies C. trachomatis and N. gonorrhoeae as major causes of PID.'],
['What is an important teaching point for trichomoniasis?',['Partners never need treatment','Sexual partners should be treated','Symptoms always occur immediately','Antibiotics are never used'],1,'The chapter recommends treatment of sexual partners, including those without symptoms.'],
['Which diagnostic method is listed for HSV lesions?',['PCR','RPR only','Pap test only','Urinalysis only'],0,'The chapter lists PCR and viral culture for HSV lesion specimens.'],
['Which infection may produce soft cauliflower-like genital growths?',['HPV','Syphilis only','Gonorrhea only','Hepatitis B'],0,'Genital warts (condylomata) can result from HPV.'],
['What is the nursing response to unexpected genital lesions in an older adult?',['Ignore them','Report to RN or health-care provider','Assume STI is impossible','Diagnose without evaluation'],1,'The chapter advises reporting findings rather than assuming older adults cannot have STIs.'],
['Which conditions may be transmitted by close body contact but are not true STIs?',['Pubic lice and scabies','Syphilis and gonorrhea','Chlamydia and HPV','Hepatitis B and C'],0,'The chapter classifies genital parasites as not true STIs, although close contact can transmit them.'],
['What does mucopurulent cervicitis affect?',['Cervix','Liver','Heart','Kidneys'],0,'Mucopurulent cervicitis is inflammation of the cervix.'],
['Which finding is associated with gonorrhea?',['Urethral discharge and dysuria','Only a painless chancre','Only gummas','Only genital warts'],0,'Gonorrhea can cause dysuria and urethral discharge.']
];
const eventCards=[['Community outreach grant! Collect $100.',100],['You organized a screening awareness fair. Collect $50.',50],['Training materials cost $40. Pay the bank.',-40],['Your clinic won a prevention award. Collect $75.',75],['Laboratory supplies cost $60. Pay the bank.',-60],['A local health campaign donated $90. Collect $90.',90]];

module.exports={spaces,questions,eventCards,colors};
