const socket=io();
const $=id=>document.getElementById(id);
const colors=['#955436','#a7d7ee','#d78ab9','#f4a344','#e74d49','#f4df49','#40a76d','#345cb8'];
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'$'+Number(n||0).toLocaleString();
let code=new URLSearchParams(location.search).get('code')||'',state=null;
$('roomCode').value=code.toUpperCase();
function watch(){code=$('roomCode').value.trim().toUpperCase();socket.emit('watch',{code},res=>{if(!res?.ok){$('error').textContent=res?.error||'Unable to connect';return;}$('error').textContent='';history.replaceState(null,'','/display.html?code='+encodeURIComponent(code));});}
$('connectForm').addEventListener('submit',e=>{e.preventDefault();watch();});
socket.on('connect',()=>{if(code)watch();});
socket.on('state',s=>{state=s;$('setup').classList.add('hide');$('main').classList.remove('hide');$('roomLabel').textContent='Room '+s.code+' · Live spectator board';render();});
function render(){const s=state;const current=s.players.find(p=>p.id===s.turn);$('status').textContent=s.ended?'🏆 Game complete':s.started?(current?current.icon+' '+current.name:'Waiting for player'):'Waiting for the host to start';$('dice').textContent=s.dice?'🎲 '+s.dice.join(' + ')+' = '+(s.dice[0]+s.dice[1]):'🎲 Dice ready';$('phase').textContent=s.started?'Status: '+s.phase:'Players joined: '+s.players.length+'/10';$('players').innerHTML=s.players.map(p=>`<div class="person ${p.id===s.turn&&!s.ended?'active':''}"><span>${p.icon} ${safe(p.name)}${p.alive?'':' (out)'}</span><span>${money(p.money)} · ${s.spaces.filter(x=>x.owner===p.id).length} deeds</span></div>`).join('');$('log').innerHTML=s.log.slice().reverse().map(x=>'<p>'+safe(x)+'</p>').join('');$('resultsPanel').classList.toggle('hide',!s.ended);if(s.ended)$('results').innerHTML=s.leaderboard.map(p=>`<div class="leader"><b>${p.rank===1?'🥇':p.rank===2?'🥈':p.rank===3?'🥉':'#'+p.rank} ${safe(p.name)}</b><span>${money(p.netWorth)}</span></div>`).join('');drawBoard();}
function drawBoard(){const s=state;const board=$('board');board.innerHTML=`<div class="center"><strong>STI-OPOLY</strong><p>🩺 Nursing School Edition</p><p>Chapter 44 · 10 Players</p><p>${s.ended?'🏆 FINAL RESULTS':s.dice?'🎲 '+s.dice.join(' + '):'🎲 READY TO PLAY'}</p><p>Room ${safe(s.code)}</p></div>`;s.spaces.forEach((space,i)=>{let row,col;if(i<=10){row=11;col=11-i;}else if(i<=20){row=11-(i-10);col=1;}else if(i<=30){row=1;col=i-19;}else{row=i-29;col=11;}const el=document.createElement('div');el.className='tile';el.style.gridRow=row;el.style.gridColumn=col;if([0,10,20,30].includes(i))el.style.background='#d5e7d9';const owner=s.players.find(p=>p.id===space.owner);el.innerHTML=`<div class="stripe" style="background:${space.group>=0?colors[space.group]:'transparent'}"></div><b>${safe(space.name)}</b><small>${space.price&&['property','rail','utility'].includes(space.type)?money(space.price):''}</small><div class="tokens">${s.players.filter(p=>p.alive&&p.pos===i).map(p=>p.icon).join('')}</div>${owner?`<span style="position:absolute;right:2px;top:2px;background:${owner.color};width:10px;height:10px;border:1px solid white;border-radius:50%"></span>`:''}`;el.title=space.name+(owner?' · Owner: '+owner.name:'');board.append(el);});}
