const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const crypto=require('crypto');
const {spaces:template,questions,eventCards}=require('./data');
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:false}});
app.use(express.static('public'));
app.get('/health',(req,res)=>res.json({ok:true}));
const rooms=new Map();
const icons=['🩺','🧪','🦠','💊','🧬','🩹','📋','🧫','🔬','💚'];
const palette=['#c46b65','#5281a8','#b17eaf','#d6a64e','#69a68a','#95785d','#8e9e46','#d77f9f','#655e9e','#4f8995'];
const uid=()=>crypto.randomBytes(12).toString('hex');
const roll=()=>crypto.randomInt(1,7);
const worth=(r,p)=>p.money+r.spaces.reduce((v,s)=>v+(s.owner===p.id?s.price:0),0);
const active=r=>r.players.filter(p=>p.alive);
const turnPlayer=r=>r.players[r.turn];
const broadcast=r=>{for(const p of r.players){const socket=io.sockets.sockets.get(p.socketId);if(socket)socket.emit('state',view(r,p.id));}io.to('display:'+r.code).emit('state',view(r,null));};
function view(r,id){return {code:r.code,self:id,host:r.host,started:r.started,ended:r.ended,players:r.players.map(p=>({id:p.id,name:p.name,color:p.color,icon:p.icon,money:p.money,pos:p.pos,alive:p.alive,jail:p.jail,freeCard:p.freeCard,connected:!!p.socketId})),spaces:r.spaces,turn:turnPlayer(r)?.id,phase:r.phase,dice:r.dice,log:r.log.slice(-18),pending:r.pending?(r.pending.player===id?{kind:'quiz',player:id,question:r.pending.question,options:r.pending.options}:{kind:'quiz',player:r.pending.player}):null,trade:r.trade,leaderboard:r.ended?r.players.map(p=>({...p,netWorth:worth(r,p)})).sort((a,b)=>b.netWorth-a.netWorth).map((p,i)=>({rank:i+1,name:p.name,netWorth:p.netWorth,alive:p.alive})):null};}
function note(r,msg){r.log.push(msg);if(r.log.length>150)r.log.shift();}
function fail(cb,msg){if(typeof cb==='function')cb({ok:false,error:msg});}
function ok(cb,extra={}){if(typeof cb==='function')cb({ok:true,...extra});}
function makeCode(){let c;do{c=crypto.randomBytes(3).toString('hex').toUpperCase()}while(rooms.has(c));return c;}
function charge(r,p,amount,credit){p.money-=amount;if(credit)credit.money+=amount;if(p.money<0){ // automatic liquidation at half value
 for(const s of r.spaces.filter(s=>s.owner===p.id).sort((a,b)=>b.price-a.price)){s.owner=null;p.money+=Math.floor(s.price/2);note(r,`${p.name} sold ${s.name} to cover debt.`);if(p.money>=0)break;}
 if(p.money<0){p.alive=false;p.money=0;for(const s of r.spaces)if(s.owner===p.id)s.owner=null;note(r,`${p.name} is bankrupt.`);}
 }}
function advance(r){if(active(r).length<=1){finish(r);return;}let n=r.turn;do{n=(n+1)%r.players.length}while(!r.players[n].alive);r.turn=n;r.phase='roll';r.doubles=0;r.dice=null;}
function finish(r){r.ended=true;r.phase='ended';note(r,'Game finished! Leaderboard is ready.');}
function requireTurn(socket,r,cb){if(!r||!r.started||r.ended||turnPlayer(r)?.socketId!==socket.id){fail(cb,'Not your turn.');return false;}return true;}
function quiz(r,p){const q=questions[crypto.randomInt(questions.length)];r.pending={kind:'quiz',player:p.id,question:q[0],options:q[1],answer:q[2],rationale:q[3]};r.phase='quiz';note(r,`${p.name} drew a nursing question.`);}
function landing(r,p,total){const s=r.spaces[p.pos];note(r,`${p.name} landed on ${s.name}.`);if(s.type==='goto'){p.pos=10;p.jail=1;r.phase='end';note(r,`${p.name} went to Detention.`);return;}
 if(s.type==='chance'||s.type==='community'){quiz(r,p);return;}
 if(s.type==='tax'){charge(r,p,s.price);r.phase='end';return;}
 if(['property','rail','utility'].includes(s.type)){
 if(s.owner===null){r.phase='buy';return;}
 if(s.owner!==p.id){const owner=r.players.find(x=>x.id===s.owner);if(owner&&owner.alive){let rent;if(s.type==='rail'){let n=r.spaces.filter(x=>x.type==='rail'&&x.owner===owner.id).length;rent=25*2**(n-1);}else if(s.type==='utility'){let n=r.spaces.filter(x=>x.type==='utility'&&x.owner===owner.id).length;rent=total*(n===2?10:4);}else{rent=Math.max(2,Math.round(s.price/10));let group=r.spaces.filter(x=>x.type==='property'&&x.group===s.group);if(group.every(x=>x.owner===owner.id))rent*=2;}charge(r,p,rent,owner);note(r,`${p.name} paid $${rent} rent to ${owner.name}.`);}}
 }r.phase='end';}
function afterMove(r,p,a,b){r.dice=[a,b];r.doubles=a===b;let old=p.pos;p.pos=(p.pos+a+b)%40;if(p.pos<old){p.money+=200;note(r,`${p.name} passed GO and collected $200.`);}landing(r,p,a+b);}
function authenticate(socket,cb){const code=String(socket.data.code||'');const r=rooms.get(code);const p=r?.players.find(p=>p.id===socket.data.playerId);if(!r||!p){fail(cb,'Join a room first.');return null;}return {r,p};}
io.on('connection',socket=>{
 socket.on('watch',({code},cb)=>{code=String(code||'').trim().toUpperCase();const r=rooms.get(code);if(!r)return fail(cb,'Room not found. Check the six-character code.');socket.join('display:'+code);socket.emit('state',view(r,null));ok(cb,{code});});
 socket.on('create',({name},cb)=>{name=String(name||'').trim().slice(0,24);if(!name)return fail(cb,'Enter a name.');const code=makeCode(),id=uid(),token=uid();const p={id,token,name,icon:icons[0],color:palette[0],money:1500,pos:0,alive:true,jail:0,freeCard:1,socketId:socket.id};const r={code,host:id,players:[p],spaces:template.map(s=>({...s,owner:null})),started:false,ended:false,turn:0,phase:'lobby',dice:null,doubles:0,pending:null,trade:null,log:[]};rooms.set(code,r);socket.data={code,playerId:id};socket.join(code);ok(cb,{code,id,token});broadcast(r);});
 socket.on('join',({code,name,token},cb)=>{code=String(code||'').trim().toUpperCase();const r=rooms.get(code);if(!r)return fail(cb,'Room not found.');let p=token&&r.players.find(p=>p.token===token);if(!p){if(r.started)return fail(cb,'Game already started. Rejoin with your original browser.');if(r.players.length>=10)return fail(cb,'Room is full.');name=String(name||'').trim().slice(0,24);if(!name)return fail(cb,'Enter a name.');if(r.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return fail(cb,'Name already taken.');const id=uid(),i=r.players.length;p={id,token:uid(),name,icon:icons[i],color:palette[i],money:1500,pos:0,alive:true,jail:0,freeCard:1,socketId:null};r.players.push(p);}if(p.socketId&&p.socketId!==socket.id){io.sockets.sockets.get(p.socketId)?.disconnect(true);}p.socketId=socket.id;socket.data={code,playerId:p.id};socket.join(code);ok(cb,{code,id:p.id,token:p.token});broadcast(r);});
 socket.on('start',(_,cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r,p}=x;if(r.host!==p.id)return fail(cb,'Only host can start.');if(r.started)return fail(cb,'Already started.');if(r.players.length<2)return fail(cb,'At least two players required.');r.started=true;r.phase='roll';note(r,'Game started!');ok(cb);broadcast(r);});
 socket.on('roll',(_,cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r,p}=x;if(!requireTurn(socket,r,cb)||r.phase!=='roll')return fail(cb,'Cannot roll right now.');const a=roll(),b=roll();if(p.jail){if(a===b){p.jail=0;note(r,`${p.name} rolled doubles and left Detention.`);afterMove(r,p,a,b);}else{p.jail++;r.dice=[a,b];if(p.jail>3){p.jail=0;charge(r,p,50);note(r,`${p.name} paid $50 after three attempts.`);afterMove(r,p,a,b);}else r.phase='end';}r.doubles=0;}else{if(a===b)r.doubles++;else r.doubles=0;if(r.doubles>=3){p.pos=10;p.jail=1;r.phase='end';r.doubles=0;note(r,`${p.name} rolled three doubles and went to Detention.`);}else afterMove(r,p,a,b);}ok(cb);broadcast(r);});
 socket.on('detention',({useCard},cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r,p}=x;if(!requireTurn(socket,r,cb)||r.phase!=='roll'||!p.jail)return fail(cb,'Not eligible.');if(useCard){if(!p.freeCard)return fail(cb,'No free cards left.');p.freeCard--;}else charge(r,p,50);p.jail=0;note(r,`${p.name} left Detention.`);ok(cb);broadcast(r);});
 socket.on('buy',({buy},cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r,p}=x;if(!requireTurn(socket,r,cb)||r.phase!=='buy')return fail(cb,'No purchase available.');const s=r.spaces[p.pos];if(s.owner!==null)return fail(cb,'Already owned.');if(buy){if(p.money<s.price)return fail(cb,'Not enough cash.');p.money-=s.price;s.owner=p.id;note(r,`${p.name} purchased ${s.name} for $${s.price}.`);}r.phase='end';ok(cb);broadcast(r);});
 socket.on('answer',({choice},cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r,p}=x;if(!requireTurn(socket,r,cb)||r.phase!=='quiz'||r.pending?.player!==p.id)return fail(cb,'No question available.');const q=r.pending;if(!Number.isInteger(choice)||choice<0||choice>=q.options.length)return fail(cb,'Invalid answer.');const correct=choice===q.answer;if(!correct){let lost=0;for(const s of r.spaces)if(s.owner===p.id){s.owner=null;lost++;}note(r,`${p.name} answered incorrectly and forfeited ${lost} properties.`);}else{note(r,`${p.name} answered correctly.`);const ev=eventCards[crypto.randomInt(eventCards.length)];charge(r,p,-ev[1]);note(r,ev[0]);}r.pending=null;r.phase='review';socket.emit('answerResult',{correct,correctAnswer:q.options[q.answer],rationale:q.rationale});ok(cb);broadcast(r);});
 socket.on('reviewDone',(_,cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r}=x;if(!requireTurn(socket,r,cb)||r.phase!=='review')return fail(cb,'No review pending.');r.phase='end';ok(cb);broadcast(r);});
 socket.on('endTurn',(_,cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r}=x;if(!requireTurn(socket,r,cb)||r.phase!=='end')return fail(cb,'Finish your action first.');advance(r);ok(cb);broadcast(r);});
 socket.on('tradeOffer',({to,give,take,giveCash,takeCash},cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r,p}=x;if(!r.started||r.ended||r.trade)return fail(cb,'Trading unavailable.');const other=r.players.find(q=>q.id===to&&q.alive&&q.id!==p.id);if(!other||!p.alive)return fail(cb,'Invalid recipient.');give=[...new Set(Array.isArray(give)?give:[])];take=[...new Set(Array.isArray(take)?take:[])];giveCash=Number(giveCash);takeCash=Number(takeCash);if(!Number.isSafeInteger(giveCash)||!Number.isSafeInteger(takeCash)||giveCash<0||takeCash<0||giveCash>p.money||takeCash>other.money)return fail(cb,'Invalid money amount.');if(give.some(i=>!Number.isInteger(i)||r.spaces[i]?.owner!==p.id)||take.some(i=>!Number.isInteger(i)||r.spaces[i]?.owner!==other.id))return fail(cb,'Property ownership changed.');if(!give.length&&!take.length&&!giveCash&&!takeCash)return fail(cb,'Offer something.');r.trade={id:uid(),from:p.id,to:other.id,give,take,giveCash,takeCash};note(r,`${p.name} proposed a trade to ${other.name}.`);ok(cb);broadcast(r);});
 socket.on('tradeReply',({accept},cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r,p}=x,t=r.trade;if(!t||t.to!==p.id)return fail(cb,'No trade offer for you.');const from=r.players.find(q=>q.id===t.from);if(accept){if(from.money<t.giveCash||p.money<t.takeCash||t.give.some(i=>r.spaces[i]?.owner!==from.id)||t.take.some(i=>r.spaces[i]?.owner!==p.id)){r.trade=null;broadcast(r);return fail(cb,'Trade no longer valid.');}from.money+=t.takeCash-t.giveCash;p.money+=t.giveCash-t.takeCash;for(const i of t.give)r.spaces[i].owner=p.id;for(const i of t.take)r.spaces[i].owner=from.id;note(r,`${p.name} accepted ${from.name}'s trade.`);}else note(r,`${p.name} declined ${from.name}'s trade.`);r.trade=null;ok(cb);broadcast(r);});
 socket.on('finish',(_,cb)=>{const x=authenticate(socket,cb);if(!x)return;const {r,p}=x;if(p.id!==r.host||!r.started)return fail(cb,'Only host can finish.');finish(r);ok(cb);broadcast(r);});
 socket.on('disconnect',()=>{const r=rooms.get(socket.data.code);const p=r?.players.find(p=>p.id===socket.data.playerId);if(p&&p.socketId===socket.id){p.socketId=null;broadcast(r);}});
});
const port=process.env.PORT||3000;if(require.main===module)server.listen(port,()=>console.log(`STI-OPOLY listening on ${port}`));
module.exports={app,server,io,rooms};
